install:
  - git submodule update --init --recursive

build_script:
  - cmd: .\build_script.bat

artifacts:
  - path: bin\x64\Release\net451\ICFGEditor.exe

deploy:
  provider: FTP
  protocol: sftp
  host: www.atarismwc.com
  folder: html/cfgeditorinstaller/
  username: pi
  password:
    secure: 5EUQJJ1H2QhydG9QQsaKaQ==