image: Visual Studio 2022

install:
  - git submodule update --init --recursive

build_script:
  - cmd: .\build_script.bat

artifacts:
  - path: bin\Release\net451\ICFGEditor.exe

environment:
  ATARISMWC_AUTH_KEY:
    secure: Ajcj3MoPREPDvB2WI67C5JWz3iVRTMJIeTtfvWEc6vk=

deploy:
  - provider: Webhook
    on:
      branch: master
    authorization: Basic $(ATARISMWC_AUTH_KEY)
    url: https://www.atarismwc.com/upload_cfgeditor_installer.php
    request_timeout: 10