init:
  - iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - git submodule update --init --recursive

build_script:
  - ps: .\build_script.ps1

artifacts:
  - path: CFGEditorInstaller.exe

deploy:
  provider: FTP
  protocol: sftp
  host: www.atarismwc.com
  folder: html/cfgeditorinstaller/
  username: pi
  password:
    secure: 5EUQJJ1H2QhydG9QQsaKaQ==